apiVersion: v1
kind: Service
metadata:
  labels:
    app: django2
  name: django-application-expose
spec:
  ports:
  - port: 8311
    protocol: TCP
    targetPort: 8000
  selector:
    app: django2
  type: NodePort